services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: go_server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017/${DB_NAME}?authSource=admin
      TOKEN_SECRET: ${TOKEN_SECRET}
      PRODUCTION: true
    networks:
      - server_network
    depends_on:
      mongodb:
        condition: service_healthy

  openAPIDocs:
    image: swaggerapi/swagger-ui
    ports:
      - "5050:8080"
    environment:
      SWAGGER_JSON: /foo/openapi.yaml
    volumes:
      - ./server/docs/openAPI.yml:/foo/openapi.yaml:ro

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: client_study4cash
    restart: unless-stopped
    ports:
      - "3000:80"

volumes:
  mongo_data:

networks:
  server_network:
    driver: bridge
